spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/dbhabit?currentSchema=adamant
    username: postgres
    password: Berik2006
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    elasticsearch:
      client:
        rest:
          uris: http://elasticsearch:9200
